spring.application.name=eventos

spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.dofikmirqclgatqlrxew
spring.datasource.password=AlejandroJeddy26
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

# Supabase Storage
supabase.url=https://dofikmirqclgatqlrxew.supabase.co
supabase.jwt-secret=Ln8G1eAdym2xXbrr1ee/UctGBvZX7ZXx7cbzwigcZYzQoR9b7riusvW3nhnajXIulaq7wM/PYwrn6XIzHV8VSQ==
supabase.storage.bucket=eventos-imagenes-de-cartelera
