spring.application.name=eventos

spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.dofikmirqclgatqlrxew
spring.datasource.password=AlejandroJeddy26
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

# Supabase Storage
supabase.url=https://dofikmirqclgatqlrxew.supabase.co
supabase.service-role-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvZmlrbWlycWNsZ2F0cWxyeGV3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NjkyODU3MSwiZXhwIjoyMDkyNTA0NTcxfQ.9BjN9YTwUrsBrboOxCDmaR3pv3v6j4fTN2-ahgxgdH0
supabase.storage.bucket=eventos-imagenes-de-cartelera
