spring.application.name=eventos

# MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/eventpass?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=dam2
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Ejecuta schema.sql al arrancar (opcional si ya lo cargas manual en Workbench)
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
